# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 181ee782104b15e85ea272adec6fea3b11d66cc3a1d4aa79776eb12f358fe0d543804be7a4f5af80e245a4c1d07b9f599f3e37f9fa540fb97f5273b4db7e8e34

test:
  secret_key_base: 3480e4829bb8dd1b51cfc2d57190e9789a07de13df5da946dfb5a5037d6fc6ee902f50a35e71b4c1e4cfe077a03861bc77fc61c41e3595543eab1987baa0d659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: e9cefbb15c2c27d725f6c920f89844785cc56cc568bf5e4ee13683cfbf3721e5f1ca042a26849ebd52dc1ea133bd169bd186220704fa8755d4621311ff209efd
